"""A synthetic fleet: thirty graded deployments and a provider that never calls anyone.

Routing logic is mostly interesting at its edges — an overloaded provider, a
context that does not fit, a tenant that may not leave its own infrastructure —
and none of those are reachable through a real API without spending money and
accepting flakiness. So the fleet here is fictional, complete, and deterministic.

**These numbers are fixtures, not measurements.** Every quality score, latency
figure and price below was generated by the formulas in this module to make the
fleet orderly. They describe no real model and must never be copied into a
production registry. They are safe to assert against precisely because they are
invented: `synth-g07` is slower than `synth-g03` because this file says so.

The fleet is built to make each routing dimension separable:

* quality, cost, context window and declared latency all rise with grade, so
  quality-first, cost-first and latency-first pick visibly different deployments;
* locality cycles local → private → external, giving each locality ten members;
* capabilities unlock as grade rises, so capability filtering has something to
  filter;
* two specialist bands score above their grade on coding and on reasoning, so
  intent-driven dimension selection is observable rather than incidental.
"""

from __future__ import annotations

import asyncio
from collections.abc import AsyncIterator, Iterator, Sequence
from dataclasses import dataclass, field
from itertools import count
from typing import Any

from llm_fabric.errors import FabricError, ProviderUnavailableError
from llm_fabric.router.capabilities import Capability, CapabilityVector
from llm_fabric.router.grades import ALL_GRADES, GRADE_COUNT, Grade
from llm_fabric.router.registry import (
    Alias,
    Locality,
    ModelRegistry,
    ModelSpec,
    PerformanceProfile,
    Placement,
    QualityScores,
)
from llm_fabric.serving.base import (
    InferenceRequest,
    Provider,
    ProviderResult,
    StreamDelta,
    StreamEnd,
    StreamEvent,
)
from llm_fabric.serving.tokens import approximate_prompt_tokens

#: Provider names, one per locality, so provider and locality filters are
#: independently testable.
LOCAL_PROVIDER = "synth_local"
PRIVATE_PROVIDER = "synth_private"
CLOUD_PROVIDER = "synth_cloud"

PROVIDERS_BY_LOCALITY: dict[Locality, str] = {
    Locality.LOCAL: LOCAL_PROVIDER,
    Locality.PRIVATE: PRIVATE_PROVIDER,
    Locality.EXTERNAL: CLOUD_PROVIDER,
}


def synthetic_model_id(grade: Grade) -> str:
    return f"synth-g{grade.ordinal:02d}"


def locality_for(grade: Grade) -> Locality:
    return (Locality.LOCAL, Locality.PRIVATE, Locality.EXTERNAL)[grade.ordinal % 3]


def capabilities_for(grade: Grade) -> CapabilityVector:
    """Capabilities unlock as grade rises. A fixture rule, not an industry fact."""
    index = grade.ordinal
    capabilities = {Capability.CHAT, Capability.STREAMING}
    thresholds: tuple[tuple[int, Capability], ...] = (
        (5, Capability.CODE),
        (8, Capability.TOOLS),
        (9, Capability.RETRIEVAL),
        (10, Capability.JSON_SCHEMA),
        (12, Capability.MULTILINGUAL),
        (14, Capability.REASONING),
        (18, Capability.VISION),
        (22, Capability.AGENT),
        (24, Capability.PREFIX_CACHE),
        (26, Capability.SPECULATIVE_DECODE),
    )
    capabilities.update(capability for floor, capability in thresholds if index >= floor)
    # A few small deployments double as embedders, so `supports_embeddings` is
    # not perfectly correlated with grade.
    if index in (1, 2, 3):
        capabilities.add(Capability.EMBEDDINGS)
    return CapabilityVector(frozenset(capabilities))


def quality_for(grade: Grade) -> QualityScores:
    """Scores that rise with grade, with two specialist bands.

    `grade.ordinal % 5 == 3` reads as a coding specialist and `% 5 == 4` as a
    reasoning specialist: each scores 0.10 above its own baseline on that one
    dimension. That is what lets a test prove the planner picked the *coding*
    score rather than the mean.

    The baseline divides by `GRADE_COUNT + 2` rather than `GRADE_COUNT` so that
    even the top band stays below 1.0. Without the headroom a specialist bonus
    at `Grade29` would be clamped away, and a test relying on it would pass for
    the wrong reason.
    """
    base = round((grade.ordinal + 1) / (GRADE_COUNT + 2), 4)
    scores = dict.fromkeys(
        (
            "reasoning",
            "coding",
            "agent",
            "math",
            "rag",
            "tool_use",
            "structured_output",
            "safety",
        ),
        base,
    )
    if grade.ordinal % 5 == 3:
        scores["coding"] = min(1.0, round(base + 0.10, 4))
    if grade.ordinal % 5 == 4:
        scores["reasoning"] = min(1.0, round(base + 0.10, 4))
    return QualityScores(**scores)


def performance_for(grade: Grade) -> PerformanceProfile:
    """Bigger is slower, monotonically, so latency-first has a clear winner."""
    index = grade.ordinal
    return PerformanceProfile(
        p50_ttft_ms=50.0 + index * 20.0,
        p95_ttft_ms=80.0 + index * 30.0,
        p99_ttft_ms=120.0 + index * 40.0,
        p50_tpot_ms=2.0 + index * 0.5,
        prefill_tokens_per_second=round(9000.0 - index * 250.0, 2),
        decode_tokens_per_second=round(300.0 - index * 8.0, 2),
    )


def synthetic_spec(grade: Grade) -> ModelSpec:
    index = grade.ordinal
    locality = locality_for(grade)
    return ModelSpec(
        id=synthetic_model_id(grade),
        provider=PROVIDERS_BY_LOCALITY[locality],
        provider_model=f"synthetic/{grade.value.lower()}",
        deployment_id=f"{synthetic_model_id(grade)}@{locality.value}",
        grade=grade,
        context_window=8192 + index * 4096,
        recommended_context_tokens=(8192 + index * 4096) // 2,
        input_cost_per_mtok=round(0.02 * (index + 1), 4),
        output_cost_per_mtok=round(0.06 * (index + 1), 4),
        estimated_compute_cost_per_hour_usd=round(0.5 * (index + 1), 4),
        capabilities=capabilities_for(grade),
        quality=quality_for(grade),
        performance=performance_for(grade),
        placement=Placement(
            region=("eu-west-1", "us-east-1", "ap-south-1")[index % 3],
            hardware=("cpu", "l4", "a100", "h100")[min(3, index // 8)],
            locality=locality,
        ),
        enabled=True,
    )


def synthetic_models() -> list[ModelSpec]:
    """All thirty deployments, one per grade."""
    return [synthetic_spec(grade) for grade in ALL_GRADES]


def synthetic_aliases() -> list[Alias]:
    models = [synthetic_model_id(grade) for grade in ALL_GRADES]
    return [
        Alias(id="synth-auto", candidates=tuple(models), policy="balanced"),
        Alias(id="synth-cheap", candidates=tuple(models), policy="cost_first"),
        Alias(id="synth-best", candidates=tuple(models), policy="quality_first"),
        Alias(id="synth-fast", candidates=tuple(models), policy="latency_first"),
        Alias(id="synth-local", candidates=tuple(models), policy="local_only"),
        Alias(id="synth-private", candidates=tuple(models), policy="private_only"),
        Alias(
            id="synth-vision",
            candidates=tuple(models),
            policy="cost_first",
            requires=frozenset({Capability.VISION}),
        ),
    ]


def synthetic_registry(
    *, models: Sequence[ModelSpec] | None = None, aliases: Sequence[Alias] | None = None
) -> ModelRegistry:
    """The whole fictional fleet, ready to route against."""
    return ModelRegistry(
        list(models if models is not None else synthetic_models()),
        list(aliases if aliases is not None else synthetic_aliases()),
    )


@dataclass(slots=True)
class SyntheticCall:
    """One recorded call, so tests can assert who was asked and in what order."""

    model: str
    streaming: bool
    prompt_tokens: int
    #: Position across *all* providers sharing a sequence, so a fallback that
    #: crosses from one provider to another still reads in the order it happened.
    sequence: int = 0


class SyntheticProvider(Provider):
    """A provider that performs no inference and fails exactly when told to.

    Failures are programmable in two ways. `fail_next` queues errors consumed one
    per call, which is how a transient outage followed by recovery is expressed —
    the shape a circuit breaker's half-open state exists to handle. `always_fail`
    is the permanent outage.
    """

    def __init__(
        self,
        name: str = "synthetic",
        *,
        latency_ms: float = 0.0,
        reply: str = "synthetic response",
        sequence: Iterator[int] | None = None,
    ) -> None:
        self.name = name
        self._latency_ms = latency_ms
        self._reply = reply
        self._sequence = sequence if sequence is not None else count()
        self._queued: dict[str, list[FabricError]] = {}
        self._permanent: dict[str, FabricError] = {}
        self.calls: list[SyntheticCall] = []

    def _record(self, model: str, *, streaming: bool, prompt_tokens: int) -> None:
        self.calls.append(
            SyntheticCall(
                model=model,
                streaming=streaming,
                prompt_tokens=prompt_tokens,
                sequence=next(self._sequence),
            )
        )

    # -- programming ---------------------------------------------------------

    def fail_next(self, model: str, error: FabricError | None = None, *, times: int = 1) -> None:
        """Queue `times` failures for `model`, consumed one per call."""
        failure = error or ProviderUnavailableError(f"synthetic outage on '{model}'")
        self._queued.setdefault(model, []).extend([failure] * times)

    def always_fail(self, model: str, error: FabricError | None = None) -> None:
        self._permanent[model] = error or ProviderUnavailableError(
            f"synthetic permanent outage on '{model}'"
        )

    def recover(self, model: str | None = None) -> None:
        if model is None:
            self._queued.clear()
            self._permanent.clear()
            return
        self._queued.pop(model, None)
        self._permanent.pop(model, None)

    def reset(self) -> None:
        self.recover()
        self.calls.clear()

    @property
    def called_models(self) -> list[str]:
        return [call.model for call in self.calls]

    def _maybe_fail(self, model: str) -> None:
        if permanent := self._permanent.get(model):
            raise permanent
        queued = self._queued.get(model)
        if queued:
            raise queued.pop(0)

    async def _delay(self) -> None:
        if self._latency_ms > 0:
            await asyncio.sleep(self._latency_ms / 1000)

    # -- Provider ------------------------------------------------------------

    async def generate(self, request: InferenceRequest) -> ProviderResult:
        prompt_tokens = approximate_prompt_tokens(list(request.messages))
        self._record(request.model, streaming=False, prompt_tokens=prompt_tokens)
        self._maybe_fail(request.model)
        await self._delay()
        text = f"{self._reply} from {request.model}"
        return ProviderResult(
            text=text,
            finish_reason="stop",
            prompt_tokens=prompt_tokens,
            completion_tokens=max(1, len(text) // 4),
            usage_reported_by_provider=True,
        )

    async def stream(self, request: InferenceRequest) -> AsyncIterator[StreamEvent]:
        prompt_tokens = approximate_prompt_tokens(list(request.messages))
        self._record(request.model, streaming=True, prompt_tokens=prompt_tokens)
        # Failing before the first token is what makes streaming failover
        # testable; once a delta is yielded the engine must not fail over.
        self._maybe_fail(request.model)
        await self._delay()
        text = f"{self._reply} from {request.model}"
        for chunk in text.split(" "):
            yield StreamDelta(text=chunk + " ")
        yield StreamEnd(
            finish_reason="stop",
            prompt_tokens=prompt_tokens,
            completion_tokens=max(1, len(text) // 4),
            usage_reported_by_provider=True,
        )


@dataclass(slots=True)
class SyntheticFleet:
    """A registry plus the providers that serve it, wired together."""

    registry: ModelRegistry = field(default_factory=synthetic_registry)
    providers: dict[str, SyntheticProvider] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.providers:
            shared = count()
            self.providers = {
                name: SyntheticProvider(name, sequence=shared)
                for name in (LOCAL_PROVIDER, PRIVATE_PROVIDER, CLOUD_PROVIDER)
            }

    def overrides(self) -> dict[str, Provider]:
        """Injectable into `ProviderFactory(overrides=...)`."""
        return dict(self.providers)

    def provider_for(self, model_id: str) -> SyntheticProvider:
        return self.providers[self.registry.get(model_id).provider]

    def fail_next(self, model_id: str, error: FabricError | None = None, *, times: int = 1) -> None:
        spec = self.registry.get(model_id)
        self.provider_for(model_id).fail_next(spec.provider_model, error, times=times)

    def always_fail(self, model_id: str, error: FabricError | None = None) -> None:
        spec = self.registry.get(model_id)
        self.provider_for(model_id).always_fail(spec.provider_model, error)

    def recover(self, model_id: str | None = None) -> None:
        if model_id is None:
            for provider in self.providers.values():
                provider.recover()
            return
        spec = self.registry.get(model_id)
        self.provider_for(model_id).recover(spec.provider_model)

    def reset(self) -> None:
        for provider in self.providers.values():
            provider.reset()

    @property
    def served(self) -> list[str]:
        """Fabric-facing model ids that were actually called, in order."""
        by_provider_model = {spec.provider_model: spec.id for spec in self.registry.all_models()}
        calls = [
            (call.sequence, by_provider_model.get(call.model, call.model))
            for provider in self.providers.values()
            for call in provider.calls
        ]
        return [model for _, model in sorted(calls, key=lambda item: item[0])]

    def describe(self) -> dict[str, Any]:
        return {
            "models": len(self.registry),
            "providers": sorted(self.providers),
            "grades": [grade.value for grade in ALL_GRADES],
        }
