apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-fabric.fullname" . }}
  labels:
    {{- include "llm-fabric.labels" . | nindent 4 }}
  {{- $prom := .Values.observability.prometheus.serviceAnnotations | default dict }}
  {{- $svc := .Values.service.annotations | default dict }}
  {{- $ann := merge $prom $svc }}
  {{- with $ann }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "llm-fabric.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
